import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';

/// Short UI sound effects (build-plan 5.8). ponytail: one tiny module, asset
/// WAVs generated by tool/gen_sfx.py, a single reused low-latency player.
/// Every play is fire-and-forget and swallows errors (e.g. no audio device)
/// so a tap never throws. [muted] is a plain ValueNotifier — no state library
/// for one bool; the top-bar toggle drives it and persists for the session.
class Sfx {
  Sfx._();

  static final ValueNotifier<bool> muted = ValueNotifier(false);

  static final AudioPlayer _player = AudioPlayer()
    ..setReleaseMode(ReleaseMode.stop);

  static void correct() => _play('sfx/correct.wav');
  static void wrong() => _play('sfx/wrong.wav');
  static void flip() => _play('sfx/flip.wav');
  static void xp() => _play('sfx/xp.wav');

  static void _play(String asset) {
    if (muted.value) return;
    // Restart from the top each call so rapid taps still click.
    _player.play(AssetSource(asset), mode: PlayerMode.lowLatency).ignore();
  }
}
